CREATE TABLE GCG_4118_CUST_JOBS(
 BIRUNID INTEGER,
 CUSTOMER CHAR(6),
 NAME_CUSTOMER CHAR(30),
 PROJECT CHAR(7),
 PHASE CHAR(4),
 JOB CHAR(6),
 SUFFIX CHAR(3),
 PART CHAR(20),
 DESCRIPTION CHAR(30),
 DATE_ORDER DATE,
 COST NUMERIC(8,2),
 USER_1 CHAR(800),
 USER_2 CHAR(800));
